NUM_ANT = 4
PACKET_SIZE = 576
assert PACKET_SIZE % (2 * NUM_ANT) == 0
TIME_SLOTS_PER_PACKET = int(PACKET_SIZE / (2 * NUM_ANT))
PACKETS_PER_BATCH = 10
TIME_SLOTS_PER_BATCH = PACKETS_PER_BATCH * TIME_SLOTS_PER_PACKET
TRAIN_TOTAL_BATCH = 10000
VALID_TOTAL_BATCH = 2000
TEST_TOTAL_BATCH = 2000
NUM_WORKERS = 0
MAX_TASKS_PER_CHILD = 100
MAX_EPOCHS = 20000
VALID_MODEL_EVERY_EPOCHES = 1
MAX_FLIP = 5
